[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"


[env]
ESP_LOG="INFO"
SSID="your_ssid"
PASSWORD="your_ssid"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tlinkall.x",
  # "-C", "link-arg=-Trom_functions.x", # Not needed in esp-hal 1.0.0-beta.1
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
