name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the firmware'
        required: true
        default: 'dev'

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  build-firmware:
    name: Build ESP32-C3 Firmware
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src
          
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        
      - name: Install espflash
        run: |
          cargo install espflash --locked
          espflash --version
        
      - name: Build firmware
        run: |
          echo "Building firmware..."
          cargo build --release --verbose
          echo "Build completed. Checking output..."
          ls -la target/riscv32imc-unknown-none-elf/release/
        
      - name: Generate firmware binary
        run: |
          # Create output directory
          mkdir -p firmware-output

          # Generate firmware binary
          espflash save-image \
            --chip esp32c3 \
            --merge \
            --skip-padding \
            target/riscv32imc-unknown-none-elf/release/power-desk \
            firmware-output/power-desk-firmware.bin

          # Create versioned filename
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="${{ github.event.inputs.version || 'dev' }}"
          fi

          cp firmware-output/power-desk-firmware.bin firmware-output/power-desk-${VERSION}.bin

          # Generate file information
          ls -la firmware-output/
          sha256sum firmware-output/*.bin > firmware-output/checksums.txt
          
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: power-desk-firmware
          path: firmware-output/
          retention-days: 30
          
      - name: Create Release (for tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            firmware-output/power-desk-*.bin
            firmware-output/checksums.txt
          body: |
            ## Power Desk Firmware ${{ github.ref_name }}

            ### Download Instructions
            - `power-desk-${{ github.ref_name }}.bin` - Main firmware file
            - `checksums.txt` - File checksums

            ### Flashing Instructions
            1. Connect hardware (refer to project documentation)
            2. Enter download mode
            3. Flash using espflash:
               ```bash
               espflash flash power-desk-${{ github.ref_name }}.bin --monitor
               ```

            ### WiFi Configuration
            Use the web configuration tool: [Power Desk Config Tool](https://github.com/IvanLi-CN/power-desk/tree/main/web-config-tool)
          draft: false
          prerelease: false
          
  build-dev-firmware:
    name: Build Development Firmware
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src
          
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        
      - name: Install espflash
        run: |
          cargo install espflash --locked
          espflash --version
        
      - name: Build firmware
        run: |
          echo "Building firmware..."
          cargo build --release --verbose
          echo "Build completed. Checking output..."
          ls -la target/riscv32imc-unknown-none-elf/release/
        
      - name: Generate firmware binary
        run: |
          mkdir -p firmware-output

          # Get short commit hash for versioning
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)

          espflash save-image \
            --chip esp32c3 \
            --merge \
            --skip-padding \
            target/riscv32imc-unknown-none-elf/release/power-desk \
            firmware-output/power-desk-dev-latest.bin

          # Also create a versioned copy with commit hash
          cp firmware-output/power-desk-dev-latest.bin firmware-output/power-desk-dev-${TIMESTAMP}-${COMMIT_HASH}.bin

          sha256sum firmware-output/*.bin > firmware-output/checksums.txt
          
      - name: Upload development firmware
        uses: actions/upload-artifact@v4
        with:
          name: power-desk-dev-firmware
          path: firmware-output/
          retention-days: 7
          
      - name: Update development release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: dev-latest
          name: "Development Build (Latest)"
          files: |
            firmware-output/power-desk-dev-latest.bin
            firmware-output/checksums.txt
          body: |
            ## Power Desk Development Firmware (Latest)

            ⚠️ **This is a development version and may be unstable!**

            **Build Information:**
            - Build time: ${{ github.event.head_commit.timestamp }}
            - Commit: ${{ github.sha }}
            - Commit message: ${{ github.event.head_commit.message }}

            **Available Files:**
            - `power-desk-dev-latest.bin` - Latest development firmware (always updated)
            - `power-desk-dev-*-*.bin` - Versioned firmware with timestamp and commit hash

            ### Flashing Instructions
            ```bash
            espflash flash power-desk-dev-latest.bin --monitor
            ```

            ### Using Web Configuration Tool
            After flashing, you can configure WiFi using the [web configuration tool](https://github.com/IvanLi-CN/power-desk/tree/main/web-config-tool).
          draft: false
          prerelease: true
          make_latest: "false"
